Introduction To Numpy 

Basics Numpy 

In [1]:
import numpy as np

In [15]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#Get Dimension
a.ndim

1

In [8]:
b.ndim

2

In [24]:
#Get Shape
a.shape,b.shape

((3,), (2, 3))

In [12]:
#Get Type
b.dtype

dtype('float64')

In [18]:
a.dtype

dtype('int16')

In [19]:
a.itemsize

2

In [20]:
a.size,b.size

(3, 6)

In [22]:
a.nbytes,b.nbytes

(6, 48)

Accessing/Changing specific elements, rows, columns, etc

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific element [r, c] #Indexing Start from 0
a[1,5]

13

In [10]:
a[:,2]# Get a specific column

array([ 3, 10])

In [11]:
a[0,:]#Get a specific row #Indexing starts from 0

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
a[1,-2]

13

In [12]:
#[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [14]:
#3D Array
s=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(s)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Initializing Different Types of Arrays 


In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Basic Operations on Numpy

In [20]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [21]:
a+2

array([3, 4, 5])

In [22]:
a**2

array([1, 4, 9])

In [ ]:
Linear_Algebra & Statistics

In [24]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
np.min(a) , np.max(a)

(1, 3)

In [28]:
np.sum(a,axis=0)

6